### ISSUE TITLE
Failed Deploy

### ISSUE THREAD

**Issue by krackxor** [yasirarism/MissKatyPyro#280]
root@ubuntu-s-2vcpu-4gb-sgp1-01:~/MissKatyPyro# sudo docker-compose up --build
Building app
Sending build context to Docker daemon  4.271MB
Step 1/4 : FROM yasirarism/misskaty-docker:latest
 ---> 00d711b1294a
Step 2/4 : ENV HOSTNAME yasir-server
 ---> Using cache
 ---> 4eee8e5c99d6
Step 3/4 : COPY . .
 ---> aa8da82f8311
Step 4/4 : CMD ["bash", "start.sh"]
 ---> Running in 433ec19695c6
Removing intermediate container 433ec19695c6
 ---> 866a2a09e4f2
Successfully built 866a2a09e4f2
Successfully tagged misskatypyro_app:latest
Recreating misskatypyro_app_1 ... done
Attaching to misskatypyro_app_1
app_1  | [WARNING] - [28-Aug-23 19:41:59 - MissKaty - UPSTREAM_REPO_URL or UPSTREAM_REPO_BRANCH is not defined, Skipping auto update] -> [update:66]app_1  | One or more env variables missing! Exiting now.
app_1  | int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
app_1  | [WARNING] - [28-Aug-23 19:42:02 - MissKaty - UPSTREAM_REPO_URL or UPSTREAM_REPO_BRANCH is not defined, Skipping auto update] -> [update:66]app_1  | One or more env variables missing! Exiting now.
app_1  | int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
misskatypyro_app_1 exited with code 1

**Comment by yasirarism** [comment]
Use environment and fill all vars

**Comment by krackxor** [comment]
# Required Vars
API_HASH=your_api_hash_value
API_ID=your_api_id_value
BOT_TOKEN=your_bot_token_value
DATABASE_URI=mongodb+srv://your_mongodb_uri_value
LOG_CHANNEL=
**UPSTREAM_REPO_URL=https://github.com/yasirarism/MissKatyPyro
UPSTREAM_REPO_BRANCH=master**

# Optional Vars
SUDO=617426792
DATABASE_NAME=MissKatyDB
SUPPORT_CHAT=YasirPediaChannel
COMMAND_HANDLER=
USER_SESSION=
OPENAI_API=
CURRENCY_API=

Is it like this?

**Comment by yasirarism** [comment]
Yes

**Comment by etunay-mufin** [comment]
Hi API_ID is my APP_ID but I think its diffrent give me a simple please

**Comment by etunay-mufin** [comment]
[WARNING] - [01-Jul-24 05:55:32 - MissKaty - UPSTREAM_REPO_URL or UPSTREAM_REPO_BRANCH is not defined, Skipping auto update] -> [update:65]
API_ID variable is missing! Exiting now
[WARNING] - [01-Jul-24 05:55:34 - MissKaty - UPSTREAM_REPO_URL or UPSTREAM_REPO_BRANCH is not defined, Skipping auto update] -> [update:65]
API_ID variable is missing! Exiting now
[WARNING] - [01-Jul-24 05:55:35 - MissKaty - UPSTREAM_REPO_URL or UPSTREAM_REPO_BRANCH is not defined, Skipping auto update] -> [update:65]
API_ID variable is missing! Exiting now
[WARNING] - [01-Jul-24 05:55:37 - MissKaty - UPSTREAM_REPO_URL or UPSTREAM_REPO_BRANCH is not defined, Skipping auto update] -> [update:65]
API_ID variable is missing! Exiting now
[WARNING] - [01-Jul-24 05:55:41 - MissKaty - UPSTREAM_REPO_URL or UPSTREAM_REPO_BRANCH is not defined, Skipping auto update] -> [update:65]
API_ID variable is missing! Exiting now
[WARNING] - [01-Jul-24 05:55:44 - MissKaty - UPSTREAM_REPO_URL or UPSTREAM_REPO_BRANCH is not defined, Skipping auto update] -> [update:65]
API_ID variable is missing! Exiting now
[WARNING] - [01-Jul-24 05:55:49 - MissKaty - UPSTREAM_REPO_URL or UPSTREAM_REPO_BRANCH is not defined, Skipping auto update] -> [update:65]
API_ID variable is missing! Exiting now
[WARNING] - [01-Jul-24 05:55:57 - MissKaty - UPSTREAM_REPO_URL or UPSTREAM_REPO_BRANCH is not defined, Skipping auto update] -> [update:65]
API_ID variable is missing! Exiting now
[WARNING] - [01-Jul-24 05:56:11 - MissKaty - UPSTREAM_REPO_URL or UPSTREAM_REPO_BRANCH is not defined, Skipping auto update] -> [update:65]
API_ID variable is missing! Exiting now
[WARNING] - [01-Jul-24 05:56:40 - MissKaty - UPSTREAM_REPO_URL or UPSTREAM_REPO_BRANCH is not defined, Skipping auto update] -> [update:65]
API_ID variable is missing! Exiting now
[WARNING] - [01-Jul-24 05:57:37 - MissKaty - UPSTREAM_REPO_URL or UPSTREAM_REPO_BRANCH is not defined, Skipping auto update] -> [update:65]
API_ID variable is missing! Exiting now
[WARNING] - [01-Jul-24 05:58:42 - MissKaty - UPSTREAM_REPO_URL or UPSTREAM_REPO_BRANCH is not defined, Skipping auto update] -> [update:65]
API_ID variable is missing! Exiting now

**Comment by yasirarism** [comment]
> Hi API_ID is my APP_ID but I think its diffrent give me a simple please
It's same, just different name. Api id and api hash you can get it from my.telegram.org it's a unity

**Comment by yasirarism** [comment]
> [WARNING] - [01-Jul-24 05:55:32 - MissKaty - UPSTREAM_REPO_URL or UPSTREAM_REPO_BRANCH is not defined, Skipping auto update] -> [update:65] API_ID variable is missing! Exiting now [WARNING] - [01-Jul-24 05:55:34 - MissKaty - UPSTREAM_REPO_URL or UPSTREAM_REPO_BRANCH is not defined, Skipping auto update] -> [update:65] API_ID variable is missing! Exiting now [WARNING] - [01-Jul-24 05:55:35 - MissKaty - UPSTREAM_REPO_URL or UPSTREAM_REPO_BRANCH is not defined, Skipping auto update] -> [update:65] API_ID variable is missing! Exiting now [WARNING] - [01-Jul-24 05:55:37 - MissKaty - UPSTREAM_REPO_URL or UPSTREAM_REPO_BRANCH is not defined, Skipping auto update] -> [update:65] API_ID variable is missing! Exiting now [WARNING] - [01-Jul-24 05:55:41 - MissKaty - UPSTREAM_REPO_URL or UPSTREAM_REPO_BRANCH is not defined, Skipping auto update] -> [update:65] API_ID variable is missing! Exiting now [WARNING] - [01-Jul-24 05:55:44 - MissKaty - UPSTREAM_REPO_URL or UPSTREAM_REPO_BRANCH is not defined, Skipping auto update] -> [update:65] API_ID variable is missing! Exiting now [WARNING] - [01-Jul-24 05:55:49 - MissKaty - UPSTREAM_REPO_URL or UPSTREAM_REPO_BRANCH is not defined, Skipping auto update] -> [update:65] API_ID variable is missing! Exiting now [WARNING] - [01-Jul-24 05:55:57 - MissKaty - UPSTREAM_REPO_URL or UPSTREAM_REPO_BRANCH is not defined, Skipping auto update] -> [update:65] API_ID variable is missing! Exiting now [WARNING] - [01-Jul-24 05:56:11 - MissKaty - UPSTREAM_REPO_URL or UPSTREAM_REPO_BRANCH is not defined, Skipping auto update] -> [update:65] API_ID variable is missing! Exiting now [WARNING] - [01-Jul-24 05:56:40 - MissKaty - UPSTREAM_REPO_URL or UPSTREAM_REPO_BRANCH is not defined, Skipping auto update] -> [update:65] API_ID variable is missing! Exiting now [WARNING] - [01-Jul-24 05:57:37 - MissKaty - UPSTREAM_REPO_URL or UPSTREAM_REPO_BRANCH is not defined, Skipping auto update] -> [update:65] API_ID variable is missing! Exiting now [WARNING] - [01-Jul-24 05:58:42 - MissKaty - UPSTREAM_REPO_URL or UPSTREAM_REPO_BRANCH is not defined, Skipping auto update] -> [update:65] API_ID variable is missing! Exiting now

Make sure you have created .env or use environment while running docker compose
