### ISSUE TITLE
Fitur Info

### ISSUE THREAD

**Issue by Yyg-Masamba** [yasirarism/MissKatyPyro#289]
Can u add fitur this is for command /info

Extracted User info From Telegram

🆔 User ID: 6196923354
📎 Profile Link: Click Here🚪
🗣 First Name: Reaper
🗣 Last Name: Last Name not found
👨🏿‍💻 Bio: None
🌐 DC ID: 1
📸 Pictures : 1
🧐 Restricted: False
✅ Verified: False
🤖 Bot: False
👥 Common Groups: 1

**Comment by yasirarism** [comment]
For common group it is not possible, only userbot can use it

**Comment by yasirarism** [comment]
Done

**Comment by Yyg-Masamba** [comment]
Thanks a lot, sir.
