### ISSUE TITLE
Heroku Support 

### ISSUE THREAD

**Issue by arjung24** [yasirarism/MissKatyPyro#58]
Please add heroku deployment support

**Comment by yasirarism** [comment]
It's already there, use workflow method. If using app.json they will blacklist this repo

**Comment by arjung24** [comment]
If i use workflow, is there any chance to ban my heroku account??

**Comment by yasirarism** [comment]
Maybe no, it's your lucky. I have tested it before moving to VPS and working fine in heroku and railway.

**Comment by arjung24** [comment]
> Maybe no, it's your lucky. I have tested it before moving to VPS and working fine in heroku and railway. I have modify some code to make working in heroku. But I didn't give explanation in readme to prevent user abuse it.

What to do for railway deployment??
Is there any special thing to do for other user for railway deployment??

**Comment by yasirarism** [comment]
> > Maybe no, it's your lucky. I have tested it before moving to VPS and working fine in heroku and railway. I have modify some code to make working in heroku. But I didn't give explanation in readme to prevent user abuse it.
> 
> What to do for railway deployment?? Is there any special thing to do for other user for railway deployment??

Just deploy it all package is hidden in Dockerfile, I didn't check again if they added more blacklist script or not

**Comment by arjung24** [comment]
Just one question brother. What will be database_name ??
Is it the username or cluster0 or whatever i named during creation of that database??

**Comment by arjung24** [comment]
> > > Maybe no, it's your lucky. I have tested it before moving to VPS and working fine in heroku and railway. I have modify some code to make working in heroku. But I didn't give explanation in readme to prevent user abuse it.
> > 
> > 
> > What to do for railway deployment?? Is there any special thing to do for other user for railway deployment??
> 
> Just deploy it all package is hidden in Dockerfile, I didn't check again if they added more blacklist script or not. Just rename some script if they blacklist some code.

Thanks a lot brother 🙏🙏

**Comment by yasirarism** [comment]
> Just one question brother. What will be database_name ?? Is it the username or cluster0 or whatever i named during creation of that database??

You can fill it as you like

**Comment by arjung24** [comment]
> > Just one question brother. What will be database_name ?? Is it the username or cluster0 or whatever i named during creation of that database??
> 
> You can fill it as you like

Ohh thanks brother. It was great help. Thanks 👍
